Add dispatcher components
wormhole-foundation/wormhole-solidity-sdk pull request #66
Opened 2024-10-22 22:57 UTC by AgusVelez5

2024-10-23 15:01 UTC, solanoepalacio approved these changes

2024-11-18 23:53 UTC, nonergodic commented on .gitmodules
The Solidity SDK should not depend on other SDKs by default but should remain standalone unless there's a really good reason to change that.

2024-11-18 23:55 UTC, nonergodic commented on src/TransferUtils.sol
> +import {IERC20} from "@openzeppelin/token/ERC20/IERC20.sol";
This should use the IERC20 include pattern explained in the README.

2024-11-18 23:55 UTC, nonergodic commented on src/TransferUtils.sol
> + */
Redundant comment.

2024-11-18 23:58 UTC, nonergodic commented on src/TransferUtils.sol
The file name is awkward. I think it's good not to just pile all the code into a single util file, but having awkwardly named <Something>Utils.sol files next to a generic Utils.sol is not the answer. The answer that scales and is clean is to create a utils subdirectory and have the individual files live in there and then expose their totality through a Utils.sol in the root directory.

2024-11-18 23:58 UTC, nonergodic commented on src/dispatcherComponents/SweepTokens.sol
> +   */
Redundant comment.

2024-11-18 23:59 UTC, nonergodic commented on src/dispatcherComponents/AccessControl.sol
> +   */
redundant comment.

2024-11-18 23:59 UTC, nonergodic commented on src/dispatcherComponents/AccessControl.sol
> +   */
redundant comment.

2024-11-18 23:59 UTC, nonergodic commented on src/dispatcherComponents/Upgrade.sol
> +   */
redundant comment.

2024-11-18 23:59 UTC, nonergodic commented on src/dispatcherComponents/Upgrade.sol
> +   */
redundant comment.

2024-11-19 00:02 UTC, nonergodic commented on src/dispatcherComponents/ids.sol
Inconsistent casing of Filename - should be Ids.sol.

2024-11-19 00:02 UTC, nonergodic commented on src/dispatcherComponents/AccessControl.sol
> +  function dispatchExecAccessControl(bytes calldata data, uint256 offset, uint8 command) internal returns (bool, uint256) {
does not adhere to 100 char max line length

2024-11-19 00:04 UTC, nonergodic commented on src/dispatcherComponents/Upgrade.sol
> +    if (senderHasAuth() != Role.Owner)
this should use `senderRole()` instead of `senderHasAuth()`

2024-11-19 00:04 UTC, nonergodic commented on src/dispatcherComponents/Upgrade.sol
> +    if (senderHasAuth() != Role.Owner)
this should use `senderRole()` instead of `senderHasAuth()`

2024-11-19 00:06 UTC, nonergodic commented on src/dispatcherComponents/AccessControl.sol
> +    if (state.owner != msg.sender)
unconventional order comparison. Should be `msg.sender != state.owner` to be consistent and match convention.

2024-11-19 00:06 UTC, nonergodic commented on src/dispatcherComponents/AccessControl.sol
> +  if (Role.None == role)
unconventional order comparison. Should be `role == Role.None` to match expectation.

2024-11-19 00:07 UTC, nonergodic commented on src/dispatcherComponents/AccessControl.sol
> +    if (state.pendingOwner != msg.sender)
Inconsistent order comparison.

2024-11-19 00:11 UTC, nonergodic commented on src/dispatcherComponents/AccessControl.sol
> +  function dispatchQueryAccessControl(bytes calldata data, uint256 offset, uint8 query) view internal returns (bool, bytes memory, uint256) {
inconsistent use of `uint256` and `uint`.

2024-11-19 00:12 UTC, nonergodic commented on src/dispatcherComponents/AccessControl.sol
> +  function dispatchExecAccessControl(bytes calldata data, uint256 offset, uint8 command) internal returns (bool, uint256) {
inconsistent use of `uint256` and `uint`. In the original code `uint` is used for essentially unbounded uint values, akin to `size_t` while `uint256` puts an emphasis on the importance of the datatype (like in a wire format, or for a value that is defined to be 256 bit).

2024-11-19 00:27 UTC, nonergodic commented on src/TransferUtils.sol
> +  if (amount == 0) return;
Was there a deliberate choice to short-circuit zero value native token transfers but allow them for ERC20s? Do we rely anywhere on an ERC20 Transfer event even for zero value transfers?

2024-11-19 00:38 UTC, nonergodic approved these changes

2024-11-19 14:30 UTC, scnale requested changes
I'm marking this as request changes because I'm making some adjustments but have to go away. Reach out to me if I leave this hanging for too long.

2024-11-19 14:30 UTC, scnale commented on README.md
> +This SDK comes with its own IERC20 interface and SafeERC20 implementation. Given that projects tend to combine different SDKs, there's often this annoying issue of clashes of IERC20 interfaces, even
```suggestion
This SDK comes with its own IERC20 interface and SafeERC20 implementation. Given that projects tend to combine different SDKs, there's often this annoying issue of clashes of IERC20 interfaces, even though they are effectively the same. We handle this issue by importing `IERC20/IERC20.sol` which allows remapping the `IERC20/` prefix to whatever directory contains `IERC20.sol` in your project, thus providing an override mechanism that should allow dealing with this problem seamlessly until forge allows remapping of individual files. The same approach is used for SafeERC20.
```

2025-01-16 20:01 UTC, nonergodic approved these changes
high time to pull this in. I'll make a few more changes later.

2025-01-16 20:04 UTC, merged