Hashing without memory allocations
wormhole-foundation/wormhole-solidity-sdk pull request #69
Opened 2024-11-06 14:12 UTC by scnale

This adds a few functions that allow the user to hash without extra memory allocations.

This doesn't include calldata variants because they would be pointless: the `KECCAK256` instruction only operates with data in memory so a copy to memory would be necessary anyway.

2024-11-06 18:25 UTC, AgusVelez5 commented
I got the idea that have the calldata variant is pointless but with the current implementation of `keccak256SubarrayUnchecked` and `keccak256Subarray` if we are working on the calldata, we will not be copying the whole bytes to memory? 
Could there be a way to avoid that and copy only the necessary bytes, like making a slice, saving it in memory and then using it?

2024-11-06 18:37 UTC, scnale commented
Ah, you're right. It might be worth adding a calldata variant in that case.

2024-11-07 15:17 UTC, scnale commented
Actually, I think it's not necessary. You can slice the calldata buffer and it'll copy just the slice, not the whole buffer.

2024-11-07 15:25 UTC, AgusVelez5 commented
Yeah, that's true but the user should be aware of that. The common way we usually use the `BytesParsingLib` is doing the operations directly over the encoded buffer. Maybe if we offer the functions outside the lib, like utils makes you pay more attention.

2024-11-07 15:33 UTC, scnale commented
I don't think we should add functions without good reason. Every new piece of code means more maintenance in the long run. Harder to read codebase, etc.

2024-11-14 17:45 UTC, nonergodic requested changes

2024-11-14 17:45 UTC, nonergodic commented on src/libraries/BytesParsing.sol
> +    uint pastTheEndOffset = offset + length;
Should use `unchecked` math to be inline with the rest of the library.

2024-12-29 14:55 UTC, scnale commented
When reviewing this PR after the latest changes I realized something: it's actually useful to have a calldata variant because we can use the space after the free memory pointer to copy the data, hash it and then return the result. The good thing about this is that we don't consume a fragment of the memory while respecting the memory model.

2024-12-29 21:47 UTC, nonergodic approved these changes
Love it!

2024-12-29 22:31 UTC, nonergodic commented
One thought:
The current signature of `function keccak256SliceCdUnchecked(bytes calldata encoded, uint offset, uint length)` is in line with the `memory` version which is good.

Otoh, since slicing `calldata` is [now](https://github.com/wormhole-foundation/wormhole-solidity-sdk/pull/76) cheap, one could reduce the signature to just `function keccak256Cd(bytes calldata encoded)` and rely on composition with `BytesParsing.sliceCdUnchecked` (using Solidity's `[start:end]` syntax would introduce checks).

Would have the small advantage that hashing a full `bytes calldata` is cheaper because you don't have to manually specify offset and length when you don't need it, and save gas by not pushing it on the stack and have that add.

2024-12-30 13:44 UTC, scnale commented
Hm, makes sense. I'll do that then.

2024-12-31 07:12 UTC, merged